load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "SpaceGramMessageShot",
    module_name = "SpaceGramMessageShot",
    srcs = glob(["*.swift"]),
    copts = ["-warnings-as-errors"],
    sdk_frameworks = ["UIKit"],
    visibility = ["//visibility:public"],
)
