load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "SpaceGramMigration",
    module_name = "SpaceGramMigration",
    srcs = glob(["*.swift"]),
    copts = ["-warnings-as-errors"],
    visibility = ["//visibility:public"],
)
